### PR TITLE
Updated ML Metadata proto to v0.22.1

### PR DESCRIPTION
**Pull request by dushyanthsc**
Updated ML Metadata proto to v0.22.1

### CODE REVIEW

**Review by avdaredevil — APPROVED** [review]
/lgtm

@Bobgy can you PTAL

**Comment by dushyanthsc** [comment]
@avdaredevil This change requires generating type-script files, Kwasi was going to help do that but since he is OOF, if you could help that would be great, otherwise, we will have to wait till Kwasi gets back.

cc: @kwasi

**Comment by Bobgy** [comment]
/lgtm
/approve

Sure, let's update proto first.
Let's wait for kwasi to generate typescript client, and probably also update the documentation because we couldn't figure out by ourselves.

**Comment by Bobgy** [comment]
Part of https://github.com/kubeflow/pipelines/issues/4013

**Pull request merged**
