### PR TITLE
Fixes from bug bash and integration with kubeflow/metadata

### PR DESCRIPTION
**Pull request by kwasi**
/kind feature
/area metadata
/area front-end
/assign avdaredevil

## Description

This PR adds changes that went into the mlmd code in kubeflow/metadata while this repo was being setup. It also contains changes that were made while create a PR to convert kubeflow/metadata to use the new kubeflow/frontend repo.

This PR needs to go in for: https://github.com/kwasi/metadata/tree/integrate-frontend-pr to be merged.

## Changes

There should be no changes in this PR, visually or logic wise

## Validation

Built a docker image and deployed: https://kubeflow-ui-07.endpoints.kwasinti-kubeflow-dev.cloud.goog/

## Note

* I'm not sure why GitHub shows this PR as having 33 commits when 27 of them are identical to PRs in kubeflow/frontend:master. New changes are everything after 4f6dc2b

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/frontend/8)

### CODE REVIEW

**Comment by jlewi** [comment]
I will let @avdaredevil review this

**Comment by avdaredevil** [comment]
Hint: Use `/cc` for reviewers and `/assign` for whoever is performing the task :)

**Review by avdaredevil — APPROVED** [review]
Looks good! I didn't go through the older commits assuming they're the same from #1 and #3

**Comment by kwasi** [comment]
> Hint: Use `/cc` for reviewers and `/assign` for whoever is performing the task :)

Thanks, this always gets me.

**Pull request merged**
