### PR TITLE
Exclude build artifacts from package via gitignore

### PR DESCRIPTION
**Pull request by snekkalapudi**
Github issue: https://github.com/kubeflow/frontend/issues/7
Adding `build/` to `.gitignore`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/frontend/43)

### CODE REVIEW

**Comment by Bobgy** [comment]
Hi @snekkalapudi, it's not enough just excluding it, now build dir is required by this repo's consumers

**Review by jlewi — CHANGES_REQUESTED** [review]
Looks like this PR should be closed.

**Pull request closed without merging**
