### PR TITLE
Export more MLMD types

### PR DESCRIPTION
**Pull request by Realsen**
* Export Context, GetExecutionByTypeAndName and GetExecutionsByContext protos
* MetadataStoreServicePromiseClient no longer has optional credential and options, as of PR #29 , so explicitly set them

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/frontend/30)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Sorry, can you also export the following types:

```
ContextType
```

```
GetContextTypeRequest
GetContextTypeResponse
GetContextsByTypeRequest
GetContextsByTypeResponse
GetContextsRequest
GetContextsResponse
```

**Comment by neuromage** [comment]
@abhi-g @kwasi @jlewi @avdaredevil could one of you please help to approve this PR?

**Comment by Bobgy** [comment]
The change is incomplete, we should also rebuild https://github.com/kubeflow/frontend/blob/master/package.json#L6.

**Pull request merged**
