### PR TITLE
[Lineage] Stable loading UX

### PR DESCRIPTION
**Pull request by Bobgy**
Issue reported in https://github.com/kubeflow/pipelines/issues/3648

Demos
the bug: https://youtu.be/DYsIrpgaucg
this PR: https://youtu.be/-o6qxTK5vGQ
screenshot:
BC2o3mBY4iS

This PR stablizes loading UX.

Changes:
* target column is updated after all data loaded, so we won't see a intermediate state that the graph mismatches target column and side columns
* add a loading icon and grey overlay on top of the UI when it's loading

~~This is branched from https://github.com/kubeflow/frontend/pull/47. So we must merge #47 first.~~ UPDATE, #47 has been merged.

### CODE REVIEW

**Comment by jlewi** [comment]
/hold
Until #47 is merged

Drive by LGTM
/lgtm

**Comment by Bobgy** [comment]
/unhold
/approve

@jlewi, @avdaredevil and @kwasi for lgtm

**Comment by jlewi** [comment]
/lgtm
/approve
/hold

You can remove the hold if you don't want to wait from some with front end experience to review this.

**Review by avdaredevil — APPROVED** [review]

**Comment by avdaredevil** [comment]
Looks great @Bobgy! Thanks for making this change! 🎉 

Were there any tests that could be updated to incorporate your new changes?

Another note (completely optional): Could we make the spinner slightly bigger?

/lgtm
/approve

**Comment by Bobgy** [comment]
@avdaredevil Sure, I will update the spinner size.

Regarding tests, I am blocked by
```
TypeError: fsevents is not a function
    at new FSEventsWatcher (/Users/gongyuan/kfp/@kubeflow/frontend/node_modules/jest-haste-map/build/lib/FSEventsWatcher.js:162:20)
```
any ideas?

EDIT: I removed node_modules, package-lock.json and reinstalled all modules, fixed the issue for me.

**Comment by Bobgy** [comment]
Hi @avdaredevil, I did the following updates:
* Made spinner bigger
* Updated snapshots (I think they are out of sync, the snapshot diff is not related to my PR)
* I don't find tests for LineageView, so I'd leave that for future

**Comment by avdaredevil** [comment]
Awesome, looks good. Thanks for updating the notes. I am cool with the change as-is. So:

/lgtm
/approve

**Pull request merged**
