### PR TITLE
[MLMD] Backport MLMD Utils and APIs added to Pipelines since Jan 8

### PR DESCRIPTION
**Pull request by kwasi**
/assign @kwasi 
/cc @avdaredevil 
/area front-end

This PR backports changes made to Util classes that were migrated to kubeflow/frontend while developing the bug bash build with LineageView based on a Jan 8th build.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/frontend/23)

### CODE REVIEW

**Comment by kwasi** [comment]
/hold

Waiting to merge latest master and verify in Pipelines and Metadata images

**Comment by avdaredevil** [comment]
Note for these PRs, instead of merging `master` everytime into your branch for updates, use `rebase` instead:

A complete example:
```shell
git checkout master
git pull prod master;git push
git checkout <my-branch>
git rebase master
```

**Comment by kwasi** [comment]
@avdaredevil Ready for review

**Review by avdaredevil — APPROVED** [review]

**Pull request merged**
