### PR TITLE
Migrate <LineageView> component and `mlmd` module

### PR DESCRIPTION
**Pull request by kwasi**
/area metadata
/assign @avdaredevil
/kind feature

This PR adds an `mlmd` module to allow the `<LineageView/>` component to be shared by the frontend modules of [kubeflow/metadata](https://github.com/kubeflow/metadata) and [kubeflow/pipelines](https://github.com/kubeflow/pipelines).

## Validation

The hash on this PR has been verified to work in both kubeflow/metadata and kubeflow/pipelines using forked branches that are still in flight:

### Metadata

WIP Branch: https://github.com/kwasi/metadata/tree/isolate-lineage-deps-wip

* No visual changes in kubeflow/metadata

Deployed at: https://kubeflow-ui-07.endpoints.kwasinti-kubeflow-dev.cloud.goog/

### Pipelines

WIP Branch: https://github.com/kwasi/pipelines/tree/lineage-in-kfp-wip

* [Artifact Details: Lineage Tab](https://screenshot.googleplex.com/HfKRg9NpdDm)
* [Artifact Details: Lineage Explorer](https://screenshot.googleplex.com/1djj5NBiujy.png)

Deployed at: https://2de286866441b3ac-dot-us-west1.notebooks.googleusercontent.com

Screencast: https://screencast.googleplex.com/cast/NTA0MTA4OTg2NDAwNzY4MHxiYzUzZjgwNC00Yw

## Known Issues

Will be addressed in follow-ups.

* Nulls in artifact names appear in the grid and output an empty breadcrumb to the action bar when clicked.
* Radio buttons are not always reset

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/frontend/3)

### CODE REVIEW

**Comment by avdaredevil** [comment]
Hey @kwasi looks pretty straightforward, I think that the `build/` folder should perhaps be .gitignore'd?

**Comment by kwasi** [comment]
I would like to ignore it, but as of now I haven't gotten it to build successfully in both kubeflow/metadata and kubeflow/pipelines without running into conflicts with the way they both enforce build and style rules. 

Filed #7 to address it and provide more context. 

I would like to get this initial CL checked in and address that to unblock future development.

**Comment by avdaredevil** [comment]
/hold cancel

Sounds good, I've removed the hold!

**Pull request merged**
