### PR TITLE
[BugBash][MLMD] Exec Cards updated to look drastically different

### LINKED ISSUE #9: [BugBash] Main Tracker
## About
This is the parent tracker for all bug bash related changes needed to be done

### Meta
/area metadata
/area front-end
/priority p0
/assign @avdaredevil
/assign @kwasi

### LINKED ISSUE #14: [BugBash] Make execution cards very different from Artifact cards
## About
This issue tackles the issue of execution cards being very similar to artifact cards in the UI.

## Solution
- [x] Update execution cards based on Mocks provided by @ajayalfred 
- [ ] _**Stretch:** Make edges and dots color corrected based on the status of relationship_

### Meta
/area metadata
/area front-end
/priority p1
/assign @avdaredevil
/cc @kwasi

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
- Exec cards updated to Blue Format
- Divider colors updated
- Title and description colors updated
- Tested in Grouped and Solo views
- Updated global background as per spec to `#F8F8F9`

## Screenshots:
Grouped View | Solo View
--- | ---
image | image

### Meta
/area metadata
/area front-end
/priority p0
/assign @avdaredevil
/cc @kwasi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/frontend/40)

### CODE REVIEW

**Comment by kwasi** [comment]
@avdaredevil Looks good! can you update the edge point to match the header font color per redlines?

nit: This isn't related to this PR so no need to do it here if you don't want to, but when the title overflows we don't see an ellipsis and there's padding is asymmetric.

**Comment by avdaredevil** [comment]
Hey @kwasi, thanks for taking a look. I've fixed the colors for the edges. I can't see where the ellipse doesn't show:
image

**Comment by kwasi** [comment]
/lgtm

Again, it's super minor, but for the overflow, I meant in the title of the execution card row on the grouped view. The timestamp looks like it overflows

**Pull request merged**
